apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ulqr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ulqr
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-ulqr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-ulqr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-ulqr
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ibtp-tenant/rhtap-demo-app/hacbs-test-project-ulqr@sha256:667fd06e0664de7cecd4de969a5133972d470ab237c2d81ec86f32585708a41b
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
