apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ulqr
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ibtp-tenant/rhtap-demo-app/hacbs-test-project-ulqr@sha256:667fd06e0664de7cecd4de969a5133972d470ab237c2d81ec86f32585708a41b
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
